# Generated by Django 4.0.1 on 2022-05-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('imagen', models.ImageField(upload_to='dailyDuoc/static/dailyDuoc/imagenes')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('texto', models.TextField(max_length=500, verbose_name='Texto')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idImagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyDuoc.imagen')),
            ],
        ),
    ]
