# Generated by Django 4.0.1 on 2022-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyDuoc', '0002_remove_noticia_idimagen_noticia_imagen_delete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='dailyDuoc/static/dailyDuoc/imagenes'),
        ),
    ]
